apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # Using LoadBalancer to expose the service externally.
  # (Can also use NodePort if running on a local cluster like minikube without LB support).
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
